<?php

/**
 * @var $this Clean_Cms_Block_Page_Fieldset
 */

?>

<section class="clean-section <?php echo $this->getCssClasses();?>" id="<?php echo $this->getFieldsetHtmlId();?>">
    <div class="clean-inner-wrapper">
        <?php if ($this->getFieldValue('title')): ?>
            <h2><?php echo $this->getFieldValue('title'); ?></h2>
        <?php endif; ?>
        <?php if ($this->getFieldValue('subtitle')): ?>
            <p class="large"><?php echo $this->getFieldValue('subtitle'); ?></p>
        <?php endif; ?>
        <div class="signup-wrapper">
            <input type="text" name="firstname" class="input-field first-name" placeholder="First Name">
            <input type="email" name="email" class="input-field email" placeholder="Email Address">
            <input class="button" type="submit" value="<?php echo $this->getFieldValue('button_text'); ?>" />
        </div>
        <div class="signup-error" style="display: none;"></div>
        <div class="signup-success" style="display: none;">Thanks for signing up!</div>
    </div>
</section>