<?php

/**
 * @var $this Clean_Cms_Block_Page_Fieldset
 */

?>

<div class="clean-section <?php echo $this->getCssClasses();?>" >
    <div class="clean-inner-wrapper">
        <?php if ($this->getFieldValue('title')): ?>
            <h2><?php echo $this->getFieldValue('title'); ?></h2>
        <?php endif; ?>

        <?php if ($this->getFieldValue('image')): ?>
            <div class="image-wrapper">
                <img src="<?php echo Mage::helper('cleancms/upload')->url($this->getFieldValue('image')); ?>">
            </div>
        <?php endif; ?>

        <?php if ($this->getFieldValue('paragraph')): ?>
            <?php echo $this->markdownToHtml($this->getFieldValue('paragraph')); ?>
        <?php endif; ?>
    </div>
</div>