<?php

/**
 * @var $this Clean_Cms_Block_Page_Fieldset
 */

?>

<div class="clean-section <?php echo $this->getCssClasses();?> ">
    <div class="clean-inner-wrapper">
        <?php if ($this->getFieldValue('image')): ?>
            <div class="image-wrapper">
                <img src="<?php echo Mage::helper('cleancms/upload')->url($this->getFieldValue('image')); ?>">
            </div>
        <?php endif; ?>

        <?php if ($this->getFieldValue('paragraph')): ?>
            <p><?php echo $this->getFieldValue('paragraph'); ?></p>
        <?php endif; ?>
    </div>
</div>